/*
====================================================================
|                                                                  |
|   Filca's Data Definition Language                               |
|   Dibuat Oleh :                                                  |
|      1. Muhammad Idham Ma'arif            (245150300111024)      |
|      2. Muhammad Aushaf Farras            (245150307111021)      |
|      3. Lazawardi Hadyan Indra Mudianto   (245150307111023)      |
|                                                                  |
====================================================================
*/

-- USERS: track Discord users only
CREATE TABLE Discord_User (
    UserID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    DiscordID VARCHAR2(50) UNIQUE NOT NULL
);

-- VENDORS / STORES
CREATE TABLE Toko (
    IDToko NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NamaToko VARCHAR2(255) NOT NULL,
    Deskripsi CLOB
);

-- PRODUCTS / MENU ITEMS linked to stores
CREATE TABLE Barang (
    IDBarang NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    IDToko NUMBER NOT NULL,
    Nama VARCHAR2(255) NOT NULL,
    Harga NUMBER(10,2) NOT NULL,
    Kategori VARCHAR2(100),
    CONSTRAINT fk_toko FOREIGN KEY (IDToko) REFERENCES Toko(IDToko)
);

-- ORDERS linked to users and stores
CREATE TABLE Pesanan (
    IDPesanan NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    IDPemesan NUMBER NOT NULL,
    IDToko NUMBER NOT NULL,
    TotalHarga NUMBER(10,2) NOT NULL,
    QRIS_Link CLOB,
    StatusPesanan VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    WaktuPesan TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (IDPemesan) REFERENCES Discord_User(UserID),
    CONSTRAINT fk_toko_order FOREIGN KEY (IDToko) REFERENCES Toko(IDToko),
    CONSTRAINT chk_status CHECK (StatusPesanan IN ('pending', 'dibayar', 'diproses', 'selesai', 'batal'))
);

-- ORDER DETAILS: items per order
CREATE TABLE Daftar_Pesanan (
    IDPesanan NUMBER NOT NULL,
    IDBarang NUMBER NOT NULL,
    Jumlah NUMBER DEFAULT 1,
    HargaSatuan NUMBER(10,2),
    CONSTRAINT pk_daftar_pesanan PRIMARY KEY (IDPesanan, IDBarang),
    CONSTRAINT fk_pesanan FOREIGN KEY (IDPesanan) REFERENCES Pesanan(IDPesanan),
    CONSTRAINT fk_barang FOREIGN KEY (IDBarang) REFERENCES Barang(IDBarang)
);
